version: "3.0"

services:

  nginx:
    restart: always
    privileged: true
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

