version: "3"
services:
  php-apache:
    restart: always
    privileged: true
    build: 
        context: ./docker/php-apache
        #args:
         #  - DOCKER_IMAGE=php:7.0-apache
    ports:
      - 9000:80
    links:
      - mysql:mysql
    volumes:
      - ./app:/var/www/html/
      - ./log:/var/log
    
  mysql:
    restart: always
    image: mysql
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/logs:/var/log/mysql
    ports:
      - 8086:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "TEST"
    
