version: "3.0"
services:
  php-apache:
    restart: always
    privileged: true
    image: php:7.0-apache
    ports:
      - 9000:80
    links:
      - mysql:mysql
      - mysql-php:mysql-php
    volumes:
      - ./app:/var/www/html/
      - ./log:/var/log
      
  mysql-php:
    restart: always
    image: bigtruedata/php-mysqli
    
  mysql:
    restart: always
    image: mysql
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/logs:/var/log/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    
